export PATH="/usr/local/cuda-12.4/bin:$PATH"

rm -r build

cmake -B build -D GGML_CUDA=ON -D BUILD_SHARED_LIBS=ON -D WHISPER_BUILD_TESTS=OFF -D WHISPER_BUILD_EXAMPLES=OFF -D WHISPER_BUILD_SERVER=OFF -D GGML_CUDA_NO_VMM=ON -D CMAKE_INSTALL_RPATH='$ORIGIN' -D CMAKE_BUILD_WITH_INSTALL_RPATH=ON

cmake --build build --config Release -j 4
