rm -r build

cmake -B build -D CMAKE_OSX_ARCHITECTURES='arm64;x86_64' -D GGML_BLAS=OFF -D GGML_METAL=OFF -D BUILD_SHARED_LIBS=ON -D WHISPER_BUILD_TESTS=OFF -D WHISPER_BUILD_EXAMPLES=OFF -D WHISPER_BUILD_SERVER=OFF -D CMAKE_INSTALL_RPATH='@loader_path' -D CMAKE_BUILD_WITH_INSTALL_RPATH=ON

cmake --build build --config Release -j 4
